###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: materials-demo-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootPassword
        - MYSQL_DATABASE=materials
        - MYSQL_USER=materials
        - MYSQL_PASSWORD=materialsPassword
      ports:
        - "10003:3306"

    webserver:
      image: nginx:alpine
      container_name: materials-demo-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "10000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: materials-demo-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

