<?php

use Application\Controller\MaterialGroupsController;
use Application\Controller\MaterialsController;
use Application\Controller\UnitsOfMeasureController;
?>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Grupy materiałów</h2>
            </div>
            <div class="card-body">
                <p>
                </p>

                <p><a class="btn btn-primary pull-right" href="<?= $this->url(MaterialGroupsController::ROUTE_NAME) ?>">Zarządzaj grupami &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Materiały</h2>
            </div>
            <div class="card-body">
                <p>
                </p>

                <p><a class="btn btn-primary pull-right" href="<?= $this->url(MaterialsController::ROUTE_NAME) ?>">Zarządzaj materiałami &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Jednostki miary</h2>
            </div>
            <div class="card-body">
                <p>
                </p>

                <p><a class="btn btn-primary pull-right" href="<?= $this->url(UnitsOfMeasureController::ROUTE_NAME) ?>">Zarządzaj jednostkami &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
